### ISSUE TITLE
Dynamic Programing getting out of a Matrix 

### ISSUE THREAD

**Issue by tzvog** [afred-khan/-HACKTOBERFEST2K20#130]
Given a File Path as a command line argument that holds a Matrix where each element is separated by a , and each row by \n and where each space is given a certain weight I would like to find the how to get from upper left corner to the bottom right corner using the lightest weight as possible

we will use dynamic programming to solve this issue
we will see the min to get to a previous points and from each one of those points the min it would take to get to the current point

Languages

 Python

**Comment by tzvog** [comment]
please assign this to me

**Comment by watch24hrs-iiitd** [comment]
Hey, I would also like to contribute for the same as my very first valid PR for hacktoberfest!
Could I also be assigned for the same?

**Comment by tzvog** [comment]
i merged it already
