### ISSUE TITLE
Remove the pylint test!!

### ISSUE THREAD

**Issue by afred-khan** [afred-khan/-HACKTOBERFEST2K20#381]

**Comment by hardik-dadhich** [comment]
Hi, @afred-khan will you give more description on this ? so I can help on that!

**Comment by afred-khan** [comment]
@hardik-dadhich The lint_python test often fails for every PR causing proplem.
![Screenshot from 2020-10-19 08-44-11](https://user-images.githubusercontent.com/72245672/96397515-5d938a80-11e7-11eb-9a62-380f965cae94.png)

**Comment by gill876** [comment]
@hardik-dadhich are you taking this issue? If not, please assign this issue to me.

**Comment by hardik-dadhich** [comment]
@afred-khan oh it's already assigned :(

**Comment by gill876** [comment]
> @afred-khan oh it's already assigned :(

I'm sorry :((( I thought you were gone
